name: Build Resume

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/build-resume.yaml"
      - "*"

concurrency:
  group: "pages"
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            resume/node_modules
          key: resume_node_modules-${{ hashFiles('resume/package-lock.json') }}
          restore-keys: |
            resume_node_modules-

      - name: Prepare resume page
        working-directory: resume
        run: |
          npm install
          
          npm run setup
          npm run export

      - name: Upload json artifact
        uses: actions/upload-artifact@v3
        with:
          name: resume.json
          path: resume/build/resume.json

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'gh-pages'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
